language: ruby
bundler_args: --without development
script:
- bundle exec rake lint
- bundle exec rake validate
- bundle exec rake spec SPEC_OPTS='--format documentation'
after_success:
- git clone -q git://github.com/puppetlabs/ghpublisher.git .forge-releng
- .forge-releng/publish
notifications:
  email: false
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/3477acef6dd93b015c9b
    on_success: change
    on_failure: always
sudo: false
env:
  global:
  - PUBLISHER_LOGIN=locp
  - secure: :-
       'r6Tp/drrMoHApBCKBg+1ZlKfeo8NR7RRh+71gQcbhUrvl4Murpqd00rIIuURZDa5bX8dn
       guX8bTx4euPbZnK967HCzYBrEgWzSOxAqX4QLsf7rq+OBm9qa7rZMbLjlsXTsfgA7HVSzv
       jreFcZbXOI3lzIzVlyGmFHYSWLZovMoLMtBbhb47zstn6oMR2QF7m4IW6AfOt4ss1F8TyB
       pCo3r2amtbTItItHb88xqdJPR9SWmc/iYCMTw0bfJ2kt6RheGzyhQlznFJqD8X5c+kie5F
       QMttB8JUCEULQFCxO3SEo787lR4w5jW0lKox9wdPbfaENq1NYyjdnjq3NrJE0Udu/Lg0XQ
       X/CdBn2boDuWt/Tkkwdydyl9sHADlxs4jQdz2PYCYiopEaVBt00FGMS/IDf9NSWaAttPB3
       m9mY10pBS2vRsxOYE11ev1jJ/MBEpSgs3iWQUifaxh0Eo+bt68X2Quc2uJAswpYZpfLB3K
       NC2XGQpC3LdSyssBW9e6o1SXYS9B3g2fy3k1C5nuw2f0QHtSAN6LYZC4jzGWjP3G6uxvil
       zub9tgGPRVM8ILvUi66R/B7JvcibHBU8Ex876Rl17edmWryEqIVp0zN7eEPsrKdY2MuCkK
       rXjvIcRGO0Mjr4IOWa9clfCYlJOt3SgJekbMVA2sdnVffZUhfYqTXg='
matrix:
  fast_finish: true
  include:
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
  - rvm: 2.1.6
    env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="yes"
