---
language: ruby
bundler_args: --without development
script:
  - "bundle exec rake lint"
  - "bundle exec rake syntax"
  - "bundle exec rake spec SPEC_OPTS='--format documentation'"
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/3477acef6dd93b015c9b
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
sudo: false
rvm:
  - "2.0.0"
